### ISSUE TITLE
It doesn't return emails

### ISSUE THREAD

**Issue by jvlobo** [ghaiklor/passport-github-token#160]
Even when the user accepts the read email permission, the response comes with an empty emails field.

Any clues?

**Comment by ghaiklor** [comment]
Could be that GitHub has changed the payload, so this code does not work properly anymore:

https://github.com/ghaiklor/passport-github-token/blob/dev/src/index.js#L93-L107

Try to look up the email in `_raw` or `_json` fields.

**Comment by jvlobo** [comment]
Thanks for the response @ghaiklor 
It looked into all of the fields. Apparently, Github only sends there the emails the user has set as "public"
To get the user emails there needs to be an extra API call.
That's why strategies like `passport-github` use the field **scope**: https://github.com/jaredhanson/passport-github/issues/15#issuecomment-262108779

Any changes to get something like that implemented in yours?

Thank you :)

**Comment by ghaiklor** [comment]
Well, I'm extending the `passport-oauth` to implement the strategy, AFAIU from the comments, the `scope` field is supported by `passport-oauth`. So, it should work without any changes.

**Comment by jvlobo** [comment]
As I can see in `passport-github` code. they explicitly look for the scope to do that extra call I was talking about: https://github.com/jaredhanson/passport-github/blob/f9310c70ab295a22c3bab93cf81c2c23c6a3456a/lib/strategy.js#L137

so I guess it won't work out of the box with `passport-oauth`

**Comment by ghaiklor** [comment]
Yeah, I see now.

You could make a contribution and I'll publish the update asap

**Comment by jvlobo** [comment]
I created a [pull request](https://github.com/ghaiklor/passport-github-token/pull/161) @ghaiklor 
I tested in my local with my project where I'm using **passport-github-token** and it works as expected.

**Comment by ghaiklor** [comment]
@jvlobo thanks a lot for contribution, I really appreciate it since I do not have time to support all of these packages.

I've published 2.2.0 with your changes, feel free to reopen the issue if something wrong
