### ISSUE TITLE
Github query parameters deprecation

### ISSUE THREAD

**Issue by jvlobo** [ghaiklor/passport-github-token#177]
Hello there.
I've been getting some notifications from Github about them deprecating the use of query params later this year: https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

Do you have plans for updating this on your package?

Thanks!

**Comment by ghaiklor** [comment]
Hi, at the moment I don't have free time to do that. Maybe in some foreseeable future.

If this is important to you and you have reproduced it locally, feel free to open a PR.

**Comment by jvlobo** [comment]
Thanks @ghaiklor I'll try to get something working and request a PR.

**Comment by jvlobo** [comment]
Thanks for accepting it @ghaiklor 
You need to release a new version of the package, right??

**Comment by ghaiklor** [comment]
@jvlobo yes, I'll do that ASAP. If this is critical for you, you can install it from GitHub for now.

**Comment by ghaiklor** [comment]
@jvlobo I've published new version on npm
