### ISSUE TITLE
How to get access token?

### ISSUE THREAD

**Issue by ekryski** [ghaiklor/passport-github-token#40]
This might be a dumb question but how do you get the github `access_token` in the first place? Is this lib expecting you to have gotten it through a mobile client or something first?

**Comment by ghaiklor** [comment]
@ekryski you're right. This strategy is designed to work with already gotten access token from the other side. Passport strategy received access token from your request and parses profile, etc...

**Comment by ekryski** [comment]
@ghaiklor I ended up getting it working after I asked but thanks for the clarification.

**Comment by DevandScorp** [comment]
@ekryski can you please tell me, how did you manage to get the access token? I tried to take access_token using code and some requests, but this token was useless and it didn't work
